add server remove and edit commands

diff --git a/ghost b/ghost
--- a/ghost
+++ b/ghost
@@ -16,8 +16,8 @@ then
     printf "%-25s %s\n" "ghost add"            "Add a new server"
     printf "%-25s %s\n" "ghost list"           "Show saved servers"
     printf "%-25s %s\n" "ghost <alias>"        "Connect to a server"
-    printf "%-25s %s\n" "ghost remove <alias>" "Planned for v1.1"
-    printf "%-25s %s\n" "ghost edit <alias>"   "Planned for v1.1"
+    printf "%-25s %s\n" "ghost remove <alias>" "Remove a server"
+    printf "%-25s %s\n" "ghost edit <alias>"   "Edit a Server"
     exit
 fi 
 
@@ -33,6 +33,157 @@ then
         printf "%-12s %-12s %-30s %-4s\n" "$Alias" "$Username" "$Host" "$Port"
     done < "$CONFIG_FILE"
     exit
+fi
+
+
+#REMOVE COMMAND
+if [ "$1" = "remove" ]
+then
+    if [ -z "$2" ]
+    then 
+        echo -e "${RED}[ERROR]${RESET} Usage: ghost remove <alias>"
+        exit 1
+    fi
+
+    server_name="$2"
+    if ! grep -q "^$server_name|" "$CONFIG_FILE"
+    then
+        echo -e "${RED}[ERROR]${RESET} Server not found"
+        exit 1 
+    fi
+
+    read -e -p "Remove Server '$server_name'? (y/n): " confirm 
+
+    if [ "$confirm" = "y" ]
+    then
+        temp_file=$(mktemp) 
+        grep -v "^$server_name|" "$CONFIG_FILE" > "$temp_file"
+        mv "$temp_file" "$CONFIG_FILE"
+        echo "Removed '$server_name'."
+    elif [ "$confirm" = "n" ]
+    then 
+        echo "Cancelled."
+    
+    else
+        echo -e "${RED}[ERROR]${RESET} Enter only y or n."
+    fi 
+    exit 
+fi
+
+# EDIT COMMAND
+if [ "$1" = "edit" ]
+then
+
+    if [ -z "$2" ]
+    then
+        echo -e "${RED}[ERROR]${RESET} Usage: ghost edit <alias>"
+        exit 1
+    fi
+
+    old_alias="$2"
+
+    server_data=$(grep "^$old_alias|" "$CONFIG_FILE")
+
+    if [ -z "$server_data" ]
+    then
+        echo -e "${RED}[ERROR]${RESET} Server not found"
+        exit 1
+    fi
+
+    IFS="|" read -r old_alias username ip port <<< "$server_data"
+
+    echo "Editing '$old_alias'"
+    echo "Press Enter to keep the current value."
+    echo
+
+    read -e -p "Username [$username]: " new_username
+    if [ -z "$new_username" ]
+    then
+        new_username="$username"
+    fi
+
+    read -e -p "Host/IP [$ip]: " new_ip
+    if [ -z "$new_ip" ]
+    then
+        new_ip="$ip"
+    fi
+
+    while true
+    do
+        read -e -p "Port [$port]: " new_port
+
+        if [ -z "$new_port" ]
+        then
+            new_port="$port"
+        fi
+
+        if [[ "$new_port" =~ ^[0-9]+$ ]]
+        then
+            break
+        else
+            echo -e "${RED}[ERROR]${RESET} Port must contain only numbers."
+        fi
+    done
+
+    read -e -p "Alias [$old_alias]: " new_alias
+    if [ -z "$new_alias" ]
+    then
+        new_alias="$old_alias"
+    fi
+
+    if [ "$new_alias" != "$old_alias" ] && grep -q "^$new_alias|" "$CONFIG_FILE"
+    then
+        echo -e "${RED}[ERROR]${RESET} Alias already exists."
+        exit 1
+    fi
+
+    echo
+    echo "==========Updated Details============"
+    echo "    Username: $new_username"
+    echo "    Port:     $new_port"
+    echo "    Host/IP:  $new_ip"
+    echo "    Alias:    $new_alias"
+    echo "====================================="
+
+    while true
+    do
+        read -e -p "Save these changes? (y/n): " confirm
+
+        if [ "$confirm" = "y" ]
+        then
+
+            temp_file=$(mktemp)
+
+            awk -F'|' \
+                -v old="$old_alias" \
+                -v new_alias="$new_alias" \
+                -v new_username="$new_username" \
+                -v new_ip="$new_ip" \
+                -v new_port="$new_port" \
+                'BEGIN { OFS="|" }
+                $1 == old {
+                    print new_alias, new_username, new_ip, new_port
+                    next
+                }
+                {
+                    print
+                }' "$CONFIG_FILE" > "$temp_file"
+
+            mv "$temp_file" "$CONFIG_FILE"
+
+            echo "Updated '$new_alias'."
+            exit
+
+        elif [ "$confirm" = "n" ]
+        then
+            echo "Cancelled."
+            exit
+
+        else
+            echo -e "${RED}[ERROR]${RESET} Enter only y or n."
+        fi
+
+    done
 fi
 
 #ADD COMMAND
@@ -61,11 +212,7 @@ then
 fi
 fi
 
-#COMMANDS COMMING SOON
-if [ "$1" = "remove" ]
-then 
-    echo "ghost remove: Coming soon (v1.1)"
-fi 
+
 
 if [ "$1" = "edit" ]
 then 
